logging:
    level:
        root: debug
---
spring:
    config:
        activate:
            on-profile: server
    rsocket:
        server:
            port: 7000
            transport: tcp
server:
    port: 8081
---
spring:
    config:
        activate:
            on-profile: client
server:
    port: 8080